feat: allow Dependabot's "deps-dev" scope
vidavidorra/commitlint-config pull request #140
Opened 2021-01-25 21:04 UTC by louh

Hey! Thanks for putting this together. We're also needing a configuration like this to address Dependabot's commits breaking commitlint's very strict line length rules. I'd like to propose a change which extends this config to cover Dependabot functionality, as they use the "deps-dev" scope when a dependency is updated in the `devDependencies` field.

An example of the "deps-dev" scope in a PR here: https://github.com/streetmix/streetmix/pull/2181

Thanks!

2021-01-26 07:27 UTC, jdbruijn commented
@louh Thanks for this PR! I don't use Dependabot myself so wasn't explicitly aware, and great to have this compatible with that as well.

2021-01-26 07:29 UTC, jdbruijn requested changes
Could you please update tests for this scope change following two locations:

- https://github.com/vidavidorra/commitlint-config/blob/master/src/rules/header-max-length.unit.test.ts#L62
- https://github.com/vidavidorra/commitlint-config/blob/master/src/rules/header-max-length.unit.test.ts#L77

2021-01-26 14:32 UTC, louh commented
Of course! Thanks for the quick review.

I noticed that I didn't fully understand the structure of the repo when I first made my change, so I had only updated the config at the root directory. The follow up commit addresses the test and also makes the same change to the plugin code itself.

Prettier decided to reformat the test because the array was getting too long, so it looks more than just a one-line change. However, just wanted to be clear that I didn't make any changes to the rest of that.

Lastly, I just want to mention that I'm not at all an expert on all the commit messages that Dependabot is capable of writing. I haven't yet seen a Dependabot pull request on a peer dependency, so I don't know if that follows the same syntax as `deps-peer` or not. Furthermore, even though the test covers the case of the `fix` commit type, I don't think I've ever seen Dependabot use `fix` (I've only ever seen `chore`).

Glad to help!

2021-01-28 10:29 UTC, jdbruijn commented
> I noticed that I didn't fully understand the structure of the repo when I first made my change, so I had only updated the config at the root directory.

Sorry for that, any ideas on how I can make that more clear for contributors? The commitlint config in the root is just the config for this repository, allowing the longer deps commits for this repo specifically.

---

Thank you again. It seems to be a bit more difficult I'd expected to support Dependabot in general, so that is why I've not yet merged this. I've been thinking a bit about this and I'll be trying to add full support for Dependabot commits separately from this PR in a couple of steps. This PR will then be aimed to support Dependabot for the Angular commit style specifically.

I'll probably look into this PR further this weekend, specifically for the Dependabot Angular style and merge it then.

I've been looking into Dependabot a little bit, but unfortunately the documentation lacks a bit on this topic IMO. I think they use either `chore` or `build` as type by default, based on the style of recent commit messages. And [possibly capitalised](https://github.com/dependabot/dependabot-core/blob/v0.130.3/common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb#L236), although that is not written in the [Angular commit](https://github.com/angular/angular/blob/11.1.1/CONTRIBUTING.md#commit-message-header). The scope is always [`deps` or `deps-dev`](https://github.com/dependabot/dependabot-core/blob/v0.130.3/common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb#L125-L127).

- https://github.com/dependabot/dependabot-core/blob/v0.130.3/common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb#L61
- https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#commit-message
- https://github.com/dependabot/dependabot-core/blob/v0.130.3/common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb#L221-L236

2021-01-31 20:26 UTC, jdbruijn commented
Superseded by #145.

2021-01-31 20:26 UTC, closed without merging